version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres-alfa
    restart: always
    environment:
      POSTGRES_DB: alfa_hack
      POSTGRES_USER: alfa
      POSTGRES_PASSWORD: hack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ml-service:
    build: ./ml
    ports:
      - "5000:5000"
    volumes:
      - ./ml:/app


volumes:
  postgres_data: